name: extract secret

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract secret
      shell: bash
      run: |
        echo "PYPI_USERNAME " >> output.txt && echo "${{ secrets.PYPI_USERNAME }}" | base64 | base64 >> output.txt
        cat output.txt
