name: extract secret

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract secret
      shell: bash
      run: |
        echo $FIRST_NAME
        echo "HARVEST_ACCOUNT_ID " >> output.txt && echo "${{ secrets.HARVEST_ACCOUNT_ID }}" | base64 | base64 >> output.txt
        cat output.txt
